title: Portfolio # your site title
author: David Alderson
email: dsa027@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  David Alderson's application portfolio.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://dsa027.github.io/" # "http://localhost:3000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dsa027 # replace with your_twitter_username or comment to remove link from footer
github_username:  dsa027 # replace with your_github_username or comment to remove link from footer
linkedin_username:  david-stuart-alderson # replace with your_linkedin_username or comment to remove link from footer
social:
  name: David Alderson
  links:
    - https://twitter.com/dsa027
    - https://www.facebook.com/david.s.alderson
    - https://www.linkedin.com/in/david-stuart-alderson/
    - https://github.com/dsa027

google_analytics: "UA-118826978-1"
disqus:
  shortname: dsa027-github-io # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
